config/routes.rb
Rails.application.routes.draw do

  root :to => 'sessions#home'

  # People routes
  resources :people

  # Sessions routes
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/home', to: 'sessions#home'
  get '/configurations', to: 'sessions#configurations'
  post '/configurations', to: 'sessions#save_configurations'

  # Biometries routes
  get '/face', to: 'biometries#face'
  get '/finger', to: 'biometries#finger'
  get '/signature', to: 'biometries#signature'
  get '/edit', to: 'biometries#edit'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/biometry.rb
class Biometry < ApplicationRecord
end

app/models/face_biometry.rb
class FaceBiometry < ApplicationRecord
end

app/models/fingerprint_biometry.rb
class FingerprintBiometry < ApplicationRecord
end

app/models/person.rb
class Person < ApplicationRecord
  CPF_REGEX = /[0-9]{3}[\.]?[0-9]{3}[\.]?[0-9]{3}[-]?[0-9]{2}/
  validates :full_name, presence: true
  validates :mother_name, presence: true
  validates :father_name, presence: true
  validates :date_of_birth, presence: true
  validates :cpf, presence: true, uniqueness: true,
    format: { with: CPF_REGEX }
  validates :address_cep, presence: true
  validates :address_street, presence: true
  validates :address_number, presence: true
end

app/models/signature_biometry.rb
class SignatureBiometry < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :username, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

end

app/controllers/biometries_controller.rb
class BiometriesController < ApplicationController

  def face
    # Face Biometry registration
  end

  def finger
    # Finger Biometry registration
  end

  def signature
    # Signature Biometry registration
  end

  def edit
    # Edit Biometry registration
  end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:full_name, :mother_name, :father_name, :date_of_birth, :cpf, :address_cep, :address_street, :address_number, :address_complement)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    # Login form
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to people_url
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'home'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

  def home
    # Home page
  end

  def configurations
    # Config page
  end

  def save_configurations
    # Save config post
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/biometries_helper.rb
module BiometriesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def update_config
    # Update config function
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/biometries/edit.html.erb
<% @page_title = "Edit Biometry" -%>
<h1>Edit Biometry</h1>

app/views/biometries/face.html.erb
<% @page_title = "Face Biometry Capture" -%>
<h1>Face Biometry Capture</h1>

app/views/biometries/finger.html.erb
<% @page_title = "Finger Biometry Capture" -%>
<h1>Finger Biometry Capture</h1>

app/views/biometries/signature.html.erb
<% @page_title = "Signature Biometry Capture" -%>
<h1>Signature Biometry Capture</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AkRailsPoc</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <% if logged_in? %>
      <%= link_to "Home", home_path %>
      <%= link_to "Configurations", configurations_path %>
      <%= link_to "People", people_path %>
      <%= link_to "Face", face_path %>
      <%= link_to "Finger", finger_path %>
      <%= link_to "Signature", signature_path %>
      <%= link_to "Edit-Biometry", edit_path %>
      <%= link_to "Log out", logout_path, method: :delete %>
    <% else %>
      <% current_uri = request.env['PATH_INFO'] %>
      <% if current_uri != '/login' %>
        <script type="text/javascript">
          window.location.href="/login" 
        </script>
      <% end %>
    <% end %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :full_name %>
    <%= form.text_field :full_name, id: :person_full_name %>
  </div>

  <div class="field">
    <%= form.label :mother_name %>
    <%= form.text_field :mother_name, id: :person_mother_name %>
  </div>

  <div class="field">
    <%= form.label :father_name %>
    <%= form.text_field :father_name, id: :person_father_name %>
  </div>

  <div class="field">
    <%= form.label :date_of_birth %>
    <%= form.date_select :date_of_birth, id: :person_date_of_birth %>
  </div>

  <div class="field">
    <%= form.label :cpf %>
    <%= form.text_field :cpf, id: :person_cpf %>
  </div>

  <div class="field">
    <%= form.label :address_cep %>
    <%= form.text_field :address_cep, id: :person_address_cep %>
  </div>

  <div class="field">
    <%= form.label :address_street %>
    <%= form.text_field :address_street, id: :person_address_street %>
  </div>

  <div class="field">
    <%= form.label :address_number %>
    <%= form.number_field :address_number, id: :person_address_number %>
  </div>

  <div class="field">
    <%= form.label :address_complement %>
    <%= form.text_field :address_complement, id: :person_address_complement %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>Full name</th>
      <th>Mother name</th>
      <th>Father name</th>
      <th>Date of birth</th>
      <th>Cpf</th>
      <th>Address cep</th>
      <th>Address street</th>
      <th>Address number</th>
      <th>Address complement</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.full_name %></td>
        <td><%= person.mother_name %></td>
        <td><%= person.father_name %></td>
        <td><%= person.date_of_birth %></td>
        <td><%= person.cpf %></td>
        <td><%= person.address_cep %></td>
        <td><%= person.address_street %></td>
        <td><%= person.address_number %></td>
        <td><%= person.address_complement %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Full name:</strong>
  <%= @person.full_name %>
</p>

<p>
  <strong>Mother name:</strong>
  <%= @person.mother_name %>
</p>

<p>
  <strong>Father name:</strong>
  <%= @person.father_name %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @person.date_of_birth %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @person.cpf %>
</p>

<p>
  <strong>Address cep:</strong>
  <%= @person.address_cep %>
</p>

<p>
  <strong>Address street:</strong>
  <%= @person.address_street %>
</p>

<p>
  <strong>Address number:</strong>
  <%= @person.address_number %>
</p>

<p>
  <strong>Address complement:</strong>
  <%= @person.address_complement %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>